[0m15:10:06.934859 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1060aaab0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106aafb00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106aaf8c0>]}


============================== 15:10:06.938125 | 8f9af79f-83e1-4645-94e3-d7b19357cc63 ==============================
[0m15:10:06.938125 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:10:06.938513 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/tommasosoldani/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:10:06.938903 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/tommasosoldani/Desktop/data-pipeline-thesis/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:10:06.967153 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07521617, "process_in_blocks": "0", "process_kernel_time": 0.166207, "process_mem_max_rss": "91357184", "process_out_blocks": "0", "process_user_time": 0.742141}
[0m15:10:06.967610 [debug] [MainThread]: Command `dbt run` failed at 15:10:06.967528 after 0.08 seconds
[0m15:10:06.967904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050b9b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106165700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1062f0980>]}
[0m15:10:06.968164 [debug] [MainThread]: Flushing usage events
[0m15:10:07.554384 [debug] [MainThread]: An error was encountered while trying to flush usage events
